

const country_code = [
    { value: "AR", label: "ARG" },
    { value: "BO", label: "BOL" },
    { value: "BR", label: "BRA" },
    { value: "CL", label: "CHL" },
    { value: "CO", label: "COL" },
    { value: "EC", label: "ECU" },
    { value: "GY", label: "GUY" },
    { value: "PY", label: "PRY" },
    { value: "PE", label: "PER" },
    { value: "SR", label: "SUR" },
    { value: "UY", label: "URY" },
    { value: "VE", label: "VEN" },
    { value: "US", label: "USA" },
    { value: "SV", label: "SLV" },
    { value: "PA", label: "PAN" },
    { value: "DE", label: "DEU" },
    { value: "FR", label: "FRA" },
    { value: "ES", label: "ESP" },
    { value: "IT", label: "ITA" },
    { value: "PT", label: "PRT" },
    { value: "IE", label: "IRL" },
    { value: "AT", label: "AUT" },
    { value: "GR", label: "GRC" },
    { value: "BE", label: "BEL" },
    { value: "FI", label: "FIN" },
    { value: "JP", label: "JPN" },
    { value: "GB", label: "GBR" },
    { value: "FK", label: "FLK" },
    { value: "GI", label: "GIB" },
    { value: "AU", label: "AUS" },
    { value: "KI", label: "KIR" },
    { value: "NR", label: "NRU" },
    { value: "CA", label: "CAN" },
    { value: "CH", label: "CHE" },
    { value: "LI", label: "LIE" },
    { value: "CN", label: "CHN" },
    { value: "NZ", label: "NZL" },
    { value: "CK", label: "COK" },
    { value: "NU", label: "NIU" },
    { value: "HK", label: "HKG" }
];

module.exports = country_code

